export const managerColumns = [
  {
    field: "image",
    headerName: "Image",
    width: 180,
    renderCell: (param) => {
      return (
        <div className="cellWithImg">
          <img src={/*param.row.photo*/ "https://img.freepik.com/free-vector/businessman-character-avatar-isolated_24877-60111.jpg?w=740&t=st=1686742697~exp=1686743297~hmac=2332b27b2c39602256581e4bc382e0bcdf087b6e2774488c029992dcc00e98e4"} className="cell" />
        </div>
      );
    },
  },
  { field: "name", headerName: "Firstname", width: 150 },
  { field: "surname", headerName: "Surname", width: 150 },
  { field: "email", headerName: "Email", width: 200 },
  { field: "companyName", headerName: "Company Name", width: 200 },
  { field: "taxNumber", headerName: "Tax Number", width: 200 },
  { field: "status", headerName: "Status", width: 150 },
  { field: "userId", headerName: "UserId", width: 250 },
];

export const managerRows = [
  {
    id: 1,
    firtName: "Melihcan",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Ozturk",
    email: "melihcan@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 2,
    firtName: "Berkin",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Yardımcı",
    email: "berkin@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 2,
    firtName: "Berkin",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Yardımcı",
    email: "berkin@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 2,
    firtName: "Berkin",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Yardımcı",
    email: "berkin@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 2,
    firtName: "Berkin",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Yardımcı",
    email: "berkin@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 2,
    firtName: "Berkin",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Yardımcı",
    email: "berkin@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 2,
    firtName: "Berkin",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Yardımcı",
    email: "berkin@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 2,
    firtName: "Berkin",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Yardımcı",
    email: "berkin@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 2,
    firtName: "Berkin",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Yardımcı",
    email: "berkin@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 2,
    firtName: "Berkin",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Yardımcı",
    email: "berkin@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 2,
    firtName: "Berkin",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Yardımcı",
    email: "berkin@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 2,
    firtName: "Berkin",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Yardımcı",
    email: "berkin@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 2,
    firtName: "Berkin",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Yardımcı",
    email: "berkin@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 2,
    firtName: "Berkin",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Yardımcı",
    email: "berkin@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 2,
    firtName: "Berkin",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Yardımcı",
    email: "berkin@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 2,
    firtName: "Berkin",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Yardımcı",
    email: "berkin@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 2,
    firtName: "Berkin",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Yardımcı",
    email: "berkin@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 2,
    firtName: "Berkin",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Yardımcı",
    email: "berkin@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 2,
    firtName: "Berkin",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Yardımcı",
    email: "berkin@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 2,
    firtName: "Berkin",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Yardımcı",
    email: "berkin@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 2,
    firtName: "Berkin",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Yardımcı",
    email: "berkin@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },

  {
    id: 12,
    firtName: "Berkin",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Yardımcı",
    email: "berkin@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 22,
    firtName: "Berkin",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Yardımcı",
    email: "berkin@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 32,
    firtName: "Berkin",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Yardımcı",
    email: "berkin@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 6,
    firtName: "Buse",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Çankaya",
    email: "berkin@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 66,
    firtName: "Buse",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Çankaya",
    email: "berkin@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 3,
    firtName: "Furkan Türkmen",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Can",
    email: "melihcan@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 4,
    firtName: "Ali ",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    surname: "Ogutcen",
    email: "aliogutcen@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
  {
    id: 5,
    firtName: "Mert",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",

    surname: "Namsal",
    email: "mertnamsal@gmail.com",
    phone: 5555555555,
    address: "Tüysüzler mahallesi Örnek Sokak No:2/2b",
  },
];
